title = "Phil Stevens Guiding"
baseURL = "/"
languageCode = "en-uk"
googleAnalytics = "UA-131145127-1"
disqusShortname = "philstevensguiding"
inst_access = "4743511319.1677ed0.e10f14134c984a0d88bbbaa795b5d5b0"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = true

[menu]

  [[menu.header]]
    weight = 2
    name = "About Phil"
    url = "/about/"
  [[menu.header]]
    weight = 3
    name = "Blog"
    url = "/blog/"
  [[menu.header]]
    weight = 4
    name = "Contact"
    url = "/contact/"
 

  [[menu.footer]]
    weight = 1
    name = "About Phil"
    url = "/about/"
  [[menu.footer]]
    weight = 2
    name = "Contact"
    url = "/contact/"
  [[menu.footer]]
    weight = 3
    name = "Blog"
    url = "/blog/"
 

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "2 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Phil Stevens Guiding"
    subtitle = "Rock<br/>Ice<br/>Snow"

  [params.wrapper]
    enable = true
   
  [params.blog]
    enable = true
    title = "The Blog"
    subtitle = "Adventures, gear and ideas"
	
  [params.about]
    enable = true
	title = "About Phil"
    subtitle = "An introduction to your guide"
	intro = "Hello and welcome"
	italic = "I'm a professional mountaineer and IFMGA guide based in Tromsø, Northern Norway, working full-time in the mountains as a guide and instructor. I'm a NORTIND tindevegleder, an Associate member of the British Association of Mountain Guides, and a Pro member of the American Avalanche Association."
	paragraph1 = "I live in Tromsø, Northern Norway, with my partner Emily. Previously we stayed for several years near the small harbour town of Oban, Scotland. I escaped the bustle of South East England in 2007, moving to Scotland to begin a career in the outdoors. I've since lived and worked in mountain regions across the world, including the Alps, Norway and Antarctica."
	paragraph2 = "I qualified as a Mountaineering Instructor in 2010, and spent several years working as a climbing instructor at the National Ice Climbing Centre and as a senior instructor at the Outward Bound Trust. Becoming an IFMGA guide was never part of the original plan, but at some point it became almost an obsession! I was proud to complete my training at the beginning of 2023, earning the coveted IFMGA carnet through the British training scheme. When I'm not out with my own clients I also work for a few local reputable guiding companies as an associate instructor."
	historytitle = "A Brief History"
	history1 = "I started hillwalking as a kid, but as a teenager my interest shifted to climbing on the small sandstone outcrops that litter the Kent/Sussex border. I have fond memories of a trip into London on the train to buy enough gear to set up top-ropes... In hindsight this was a bit ambitious given my limited knowledge, and it all seemed pretty epic at the time. Suffice to say the learning curve was steep! Since these early forays on rock, it seems like I've barely stopped climbing (or learning) since."
	history2 = "Climbing trips with friends have now taken me all over the world, and the list of places to visit seems to get longer rather than shorter. I love adventurous places, so I spend a lot of my time climbing on sea cliffs and similar difficult-to-reach places."
	history3 = "Over the years I built up a good working knowledge of many popular climbing and skiing destinations... but it's always good to expand on the areas I 'know', so if you have a destination in mind and want a guide, get in touch - if I can't help, I will always try to point you towards someone who can."
	history4 = "Many people know me as 'Chucky' - when I was nine I had a strong resemblance to the Rugrats children's cartoon character... The name stuck, but if you prefer Phil then I'm happy with that name too!"
	
  [params.feature]
    enable = true
    title = "Phil Stevens"
	subtitle = "IFMGA Mountain Guide and Mountaineering Instructor"
	paragraph1 = "I’m a professional mountaineer, now based in Tromsø, Arctic Norway. I've also got strong ties near Oban in the West Highlands of Scotland. I've been a Mountaineering and Climbing Instructor since 2010, and qualified as an IFMGA mountain guide through the British Mountain Guides scheme. Arctic Norway, the UK, the European Alps and Antarctica are the places I know best,  but I'm always learning and exploring."
	paragraph2 = "'Phil Stevens Guiding' is about finding clients who would like to build a longer-term, highly personalised guiding relationship. I believe you get a better guided experience when you choose a guide who knows what you've done, what you are capable of, and what inspires you in the mountains. Planning on just one day with me? No problem at all, you're very welcome - but I hope I can give you a mountain experience that makes you want to come back for more!"
	[params.feature.button]
      caption = "More about Phil"
      url = "/about/"

  
  [params.call]
    enable = true
    title = "Professional mountain guiding and instruction"
    paragraph = "Rock climbing, scrambling, winter mountaineering, ski touring, ice climbing..."
	[params.call.button]
      caption = "Contact Phil"
      url = "/contact/"

  [params.service]
    enable = true
    title = "Adventures in the Mountains"
    subtitle1 = "Take a look at some of what I can offer from my base on the West Coast of Scotland. Watch this space for more international options, coming soon."
	subtitle2 = "This year, travel is still something of a sticking point. I'm intending to be in Norway until July, when I will relocate to the European Alps for the summer. Feel free to contact me for more information about options, or to talk about making a booking."
	
  [params.testimonial]	
    enable = true
	
  [params.contact]
    enable = true
    title = "Contact Phil"
    subtitle1 = "Looking for more inspiration?"  
    subtitle2 = "Need professional guidance about the right objective for you?"
	subtitle3 = "Keen to book and want to know prices? Get in touch!"
	intro1 = "Given the bespoke nature of high-quality guiding, I believe it's important to have the right information before quoting prices. Please get in touch and let me know what you're looking for - I'll be happy to give advice or to offer a quote at no obligation."
	intro2 = "Rest assured that while I pride myself on offering a top-quality product, I also believe in giving good value. As result, Phil Stevens Guiding's prices are highly competetive."
	[params.contact.form]
      name = "Your name"
      email = "Your email"
      reason = "Reason for your enquiry"
      message = "Further information - for example, your aims/abjectives, the size of your party, when you are looking to book"
      button = "Send message"
    [params.contact.box]
      title = "Contact details"
      address = "Kråkebollevegen 56, Kvaløya, Tromsø, Norway"
      addresslink = "https://maps.app.goo.gl/z5YP4QcXuvrRdfez8"
	  email = "info@philstevensguiding.com"
      phone = "+44(0)7474817841"
    [params.contact.gmap]
	  enable = true


   
   [params.thanks]
     enable = true
	 title = "Thanks for your Enquiry!"
	 subtitle = "I'll get back to you as soon as possible."
	 paragraph = "I always respond to enquiries as quickly as I can. Due to the range of locations I work in, some of which have little or no internet connectivity, this can occasionally take a little longer than I'd like - please bear with me if this is the case."
	 caption = "Return to homepage"
	 

 [params.notfound]
     enable = true
	 title = "Oops, I think you've gone off-route mate..."
	 subtitle = "The page you're looking for can't be found - please check the address or use the menu to navigate."
 	 paragraph = "If you think you've found a broken link within the site, please let me know through the contact form so I can fix it."
	 caption = "Return to homepage"
	 
[taxononmies]

	series = "series"
